/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador;
import java.awt.event.ActionListener;

/**
 *
 * @author Keren
 */
public class FRM_VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaPrincipal
     */
    Controlador controlador;
    public FRM_VentanaPrincipal(Controlador controlador) {
        initComponents();
        setLocation(400,200);
        setVisible(false);
        this.controlador=controlador;
        agregarEventos();
    }

    private FRM_VentanaPrincipal() {
    }
    
    public void agregarEventos()
    {
        this.btn_NuevaCita.addActionListener((ActionListener) controlador);
        this.btn_Ordenar.addActionListener((ActionListener) controlador);
        this.btn_Siguiente.addActionListener((ActionListener) controlador);
        
    }
    
    public void actualizarLista(String[] fichas)
    {   
        this.jl_Siguiente.setText(fichas[1]);
        this.jl_Siguiente1.setText(fichas[2]);
        this.jl_Siguiente2.setText(fichas[3]);
    }
    
    public void ordenarLista(String[] fichas)
    {
        this.jl_Siguiente.setText(fichas[1]);
        this.jl_Siguiente1.setText(fichas[2]);
        this.jl_Siguiente2.setText(fichas[3]);
    }
    
    public int enviarInformacionEdad()
    {
        int datos=0;
        datos=Integer.parseInt(jt_Edad.getText());
        return datos;
    }
    
    public void refresarVentana()
    {
        this.jl_NumCita.setText("--");
        this.jl_Siguiente.setText("--");
        this.jl_Siguiente1.setText("--");
        this.jl_Siguiente2.setText("--");
        this.jt_Nombre.setText("");
        this.jt_Edad.setText("");
        this.jrb_Normal.setSelected(false);
        this.jrb_Preferencial.setSelected(false);
    }
    
    public void refresarInformacion()
    {
        this.jt_Nombre.setText("");
        this.jt_Cedula.setText("");
        this.jt_Edad.setText("");
        this.jrb_Normal.setSelected(false);
        this.jrb_Preferencial.setSelected(false);
    }
    
    public String enviarInformacion()
    {
        String datos="";
        datos=jt_Nombre.getText();
        return datos;
    }

    public String enviarPrioridad()
    {
        String datos="";
        if(jrb_Normal.isSelected())
        {
            datos="B";
        }
        else
        {
            if(jrb_Preferencial.isSelected())
            {
                datos="A";
            }
        }
        
        return datos;
    }
    
    public void colocarCita(String cita)
    {
        jl_NumCita.setText(cita);
    }
    
    public void imprimirArea(String texto)
    {
        this.jTextArea1.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Nombre = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_Edad = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_Edad = new javax.swing.JTextField();
        jl_Tipo = new javax.swing.JLabel();
        btn_NuevaCita = new javax.swing.JButton();
        jl_NumCita = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Ordenar = new javax.swing.JButton();
        btn_Siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jrb_Normal = new javax.swing.JRadioButton();
        jrb_Preferencial = new javax.swing.JRadioButton();
        jl_Siguiente = new javax.swing.JLabel();
        jl_Siguiente1 = new javax.swing.JLabel();
        jl_Siguiente2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_Nombre.setText("Nombre:");

        jl_Cedula.setText("Cédula:");

        jl_Edad.setText("Edad:");

        jl_Tipo.setText("Tipo");

        btn_NuevaCita.setText("Nueva cita");

        jl_NumCita.setText("_ _ _ _ _");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Sistema Generador de Citas");

        btn_Ordenar.setText("Ordenar");

        btn_Siguiente.setText("Siguiente");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jrb_Normal.setText("Normal");
        jrb_Normal.setActionCommand("Normal");
        jrb_Normal.setContentAreaFilled(false);

        jrb_Preferencial.setText("Preferencial");
        jrb_Preferencial.setActionCommand("Preferencial");
        jrb_Preferencial.setContentAreaFilled(false);

        jl_Siguiente.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jl_Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jl_Siguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Siguiente.setText("---");

        jl_Siguiente1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jl_Siguiente1.setForeground(new java.awt.Color(255, 255, 255));
        jl_Siguiente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Siguiente1.setText("---");

        jl_Siguiente2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jl_Siguiente2.setForeground(new java.awt.Color(255, 255, 255));
        jl_Siguiente2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Siguiente2.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Tipo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jrb_Preferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jrb_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(114, 114, 114)
                                        .addComponent(btn_Ordenar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_Nombre)
                                            .addComponent(jl_Cedula)
                                            .addComponent(jl_Edad))
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7)
                                        .addComponent(btn_Siguiente))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btn_NuevaCita)
                                .addGap(42, 42, 42)
                                .addComponent(jl_NumCita, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_Siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_Siguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Nombre)
                            .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Cedula)
                            .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Edad)
                            .addComponent(jt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jl_Tipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_Preferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jrb_Normal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_NumCita)
                            .addComponent(btn_NuevaCita))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btn_Siguiente)
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Ordenar)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jl_Siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jl_Siguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NuevaCita;
    private javax.swing.JButton btn_Ordenar;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Edad;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_NumCita;
    private javax.swing.JLabel jl_Siguiente;
    private javax.swing.JLabel jl_Siguiente1;
    private javax.swing.JLabel jl_Siguiente2;
    private javax.swing.JLabel jl_Tipo;
    private javax.swing.JRadioButton jrb_Normal;
    private javax.swing.JRadioButton jrb_Preferencial;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Nombre;
    // End of variables declaration//GEN-END:variables

}
