/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador;
import Modelo.Nodo;
import java.awt.event.ActionListener;

/**
 *
 * @author Keren
 */
public class FRM_VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_VentanaPrincipal
     */
    Controlador controlador;
    public FRM_VentanaPrincipal() {
        initComponents();
        setLocation(400,200);
        controlador= new Controlador(this);
        agregarEventos();
        this.jrb_Normal.setSelected(true);
    }
    
    public void agregarEventos()
    {
        this.btn_NuevaCita.addActionListener((ActionListener) controlador);
        this.btn_MenorAMayor.addActionListener((ActionListener) controlador);
        this.btn_Siguiente.addActionListener((ActionListener) controlador);
    }
    
    public boolean validarCampos() {
        if(jt_Nombre.getText().isEmpty() || jt_Cedula.toString().isEmpty() ||
                jt_Edad.getText().isEmpty()){
            return false;
        }//fin if
        return true;
    }
    
    public void limpiarVentana()
    {
        this.jl_CedulaSiguiente.setText("--");
        this.jt_Nombre.setText("");
        this.jt_Edad.setText("");
        this.jrb_Normal.setSelected(true);
        this.jrb_Preferencial.setSelected(false);
    }
    
    public void limpiarDatos()
    {
        this.jt_Nombre.setText("");
        this.jt_Cedula.setText("");
        this.jt_Edad.setText("");
        this.jrb_Normal.setSelected(true);
    }//fin limpiarDatos
    
    /**
     * Se extraen los datos ingresados por el usuario
     * con la finalidad de crear un nuevo Nodo para la lista
    **/
    public Nodo getCita() {
        String nombre = jt_Nombre.getText().toString();
        int edad = Integer.parseInt(jt_Edad.getText().toString());
        int cedula = Integer.parseInt(jt_Cedula.getText().toString());
        String prioridad = this.getPrioridad();
        Nodo siguiente = null;
        return new Nodo(nombre, edad, cedula, prioridad, siguiente);
    }//fin getCita
    
    public void setCedulaSiguiente(String cedula){
        this.jl_CedulaSiguiente.setText(cedula);
    }//fin setCedulaSiguiente
    
    public String getPrioridad()
    {
        if(jrb_Preferencial.isSelected()) {
            return "Preferencial";
        }//fin if
        return "Normal";
    }//getPrioridad
    
    public void colocarCita(String cita){
        jl_CedulaSiguiente.setText(cita);
    }//fin colocarCita
    
    public void mostrarInfo(String texto){
        this.jta_Area.setText(texto);
    }//fin mostrarInfo

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jl_Nombre = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_Edad = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Cedula = new javax.swing.JTextField();
        jt_Edad = new javax.swing.JTextField();
        jl_Tipo = new javax.swing.JLabel();
        btn_NuevaCita = new javax.swing.JButton();
        jl_CedulaSiguiente = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_MenorAMayor = new javax.swing.JButton();
        btn_Siguiente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Area = new javax.swing.JTextArea();
        jrb_Normal = new javax.swing.JRadioButton();
        jrb_Preferencial = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_MayorAMenor = new javax.swing.JButton();
        jl_Cita = new javax.swing.JLabel();
        jl_Edad1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 480));
        setMinimumSize(new java.awt.Dimension(540, 480));
        setPreferredSize(new java.awt.Dimension(540, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Nombre.setText("Nombre:");
        getContentPane().add(jl_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jl_Cedula.setText("Cédula:");
        getContentPane().add(jl_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jl_Edad.setText("Fecha de asignacion:");
        getContentPane().add(jl_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(jt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 160, -1));
        getContentPane().add(jt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 160, -1));
        getContentPane().add(jt_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 160, -1));

        jl_Tipo.setText("Tipo");
        getContentPane().add(jl_Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        btn_NuevaCita.setText("Nueva cita");
        btn_NuevaCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevaCitaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_NuevaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 110, -1));

        jl_CedulaSiguiente.setText("_ _ _ _ _");
        getContentPane().add(jl_CedulaSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 290, 50));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Sistema Generador de Citas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_MenorAMayor.setText("<");
        btn_MenorAMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenorAMayorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_MenorAMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        btn_Siguiente.setText("Siguiente");
        getContentPane().add(btn_Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jta_Area.setEditable(false);
        jta_Area.setColumns(20);
        jta_Area.setRows(5);
        jScrollPane1.setViewportView(jta_Area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 480, 130));

        buttonGroup1.add(jrb_Normal);
        jrb_Normal.setText("Normal");
        jrb_Normal.setContentAreaFilled(false);
        getContentPane().add(jrb_Normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 80, -1));

        buttonGroup1.add(jrb_Preferencial);
        jrb_Preferencial.setText("Preferencial");
        jrb_Preferencial.setContentAreaFilled(false);
        getContentPane().add(jrb_Preferencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 480, 20));

        btn_MayorAMenor.setText(">");
        getContentPane().add(btn_MayorAMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        jl_Cita.setText("_ _ _ _ _ _ _ _ _ _ _ _");
        getContentPane().add(jl_Cita, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 110, -1));

        jl_Edad1.setText("Edad:");
        getContentPane().add(jl_Edad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenorAMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenorAMayorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MenorAMayorActionPerformed

    private void btn_NuevaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevaCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_NuevaCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new FRM_VentanaPrincipal().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MayorAMenor;
    private javax.swing.JButton btn_MenorAMayor;
    private javax.swing.JButton btn_NuevaCita;
    private javax.swing.JButton btn_Siguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_CedulaSiguiente;
    private javax.swing.JLabel jl_Cita;
    private javax.swing.JLabel jl_Edad;
    private javax.swing.JLabel jl_Edad1;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Tipo;
    private javax.swing.JRadioButton jrb_Normal;
    private javax.swing.JRadioButton jrb_Preferencial;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_Edad;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextArea jta_Area;
    // End of variables declaration//GEN-END:variables

}
